### ISSUE TITLE
Pull request #17 to encode body as byte sequence introduces a regression in python 2.

### ISSUE THREAD

**Issue by dknupp** [cloudera/thrift_sasl#18]
https://github.com/cloudera/thrift_sasl/pull/17 introduced a regression for python 2.x.
```
Python 2.7.10 (default, Aug 17 2018, 19:45:58)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import impala.dbapi as impyla
>>> c = impyla.connect('<redacted hostname>', auth_mechanism='GSSAPI', use_ssl=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/impyla/lib/python2.7/site-packages/impala/dbapi.py", line 150, in connect
    http_path=http_path)
  File "/tmp/impyla/lib/python2.7/site-packages/impala/hiveserver2.py", line 825, in connect
    transport.open()
  File "/Users/dknupp/Documents/code/thrift_sasl/thrift_sasl/__init__.py", line 88, in open
    self._send_message(self.OK, initial_response)
  File "/Users/dknupp/Documents/code/thrift_sasl/thrift_sasl/__init__.py", line 109, in _send_message
    body = body.encode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 1: ordinal not in range(128)
```
Under python 2, when the body is plain ASCII, calling encode() doesn't present an issue.
```
>>> 'foo'.encode()
'foo'
```
However, since the body is not always ASCII, we wind up with:
```
>>> '\x82'.encode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 0: ordinal not in range(128)
```
I suspect that the preferred fix to the original issue should be to use bytearray():
 ```
  def _send_message(self, status, body):
    header = struct.pack(">BI", status, len(body))
    if isinstance(body, str):
      body = bytearray(body)
    self._trans.write(header + body)
    self._trans.flush()
```
Test using python 2.7.10
```
Python 2.7.10 (default, Aug 17 2018, 19:45:58)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import impala.dbapi as impyla
>>> c = impyla.connect('<redacted hostname>', auth_mechanism='GSSAPI', use_ssl=True)
>>> cursor = c.cursor()
>>> cursor.execute('show databases')
>>> cursor.fetchall()
[('_impala_builtins', 'System database for Impala builtin functions'), ('default', 'Default Hive database')]
>>>
```
Test using python 3.7.2
```
Python 3.7.2 (default, Jan 13 2019, 12:50:01)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import impala.dbapi as impyla
>>> c = impyla.connect('<redacted hostname>', auth_mechanism='GSSAPI', use_ssl=True)
>>> cursor = c.cursor()
>>> cursor.execute('show databases')
>>> cursor.fetchall()
[('_impala_builtins', 'System database for Impala builtin functions'), ('default', 'Default Hive database')]
>>>
```

**Comment by dknupp** [comment]
Cc: @timarmstrong @Swixx

**Comment by adamjsawicki** [comment]
@dknupp Can this close because of #19?

**Comment by dknupp** [comment]
@adamjsawicki -- yes, thanks.
